set(ENABLE_HIP ON CACHE BOOL "")
set(HIPCC_VERSION "rocm-3.10.0" CACHE STRING "")
set(HIPCC_HOME "/opt/${HIPCC_VERSION}")

set(CMAKE_C_COMPILER   "${HIPCC_HOME}/bin/hipcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "${HIPCC_HOME}/bin/hipcc" CACHE PATH "")
set(BLT_CXX_STD "c++11" CACHE STRING "")

