set(ENABLE_HIP ON CACHE BOOL "")
set(HIPCC_VERSION "rocm-4.0.1" CACHE STRING "")

#set(CMAKE_C_COMPILER   "$ENV{ROCM_PATH}/bin/hipcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "$ENV{ROCM_PATH}/bin/hipcc" CACHE PATH "")

